name: hub-demo

services:
  velocity:
    image: ${HUB_VELOCITY_IMAGE:-ghcr.io/uebliche/hub-velocity:latest}
    container_name: hub-demo-velocity
    volumes:
      - ./docker/velocity.docker.toml:/app/velocity.toml:ro
      - ./docker/velocity.forwarding.secret:/app/forwarding.secret:ro
      - ./docker/plugins.hub:/app/plugins/hub:ro
    ports:
      - "25577:25577"
    environment:
      VELOCITY_FORWARDING_SECRET: ${VELOCITY_FORWARDING_SECRET:-secret}
    networks:
      - hub

  lobby:
    image: ${HUB_PAPER_IMAGE:-ghcr.io/uebliche/hub-paper:latest}
    container_name: hub-demo-lobby
    environment:
      VELOCITY_FORWARDING_SECRET: ${VELOCITY_FORWARDING_SECRET:-secret}
    networks:
      - hub

  ffa:
    image: ${HUB_FFA_IMAGE:-ghcr.io/uebliche/hub-ffa:latest}
    container_name: hub-demo-ffa
    environment:
      VELOCITY_FORWARDING_SECRET: ${VELOCITY_FORWARDING_SECRET:-secret}
    networks:
      - hub

  minestom:
    image: ${HUB_MINESTOM_IMAGE:-ghcr.io/uebliche/hub-minestom:latest}
    container_name: hub-demo-minestom
    environment:
      VELOCITY_FORWARDING_SECRET: ${VELOCITY_FORWARDING_SECRET:-secret}
    networks:
      - hub

networks:
  hub:
    driver: bridge

volumes:
  lobby-data:
