name: hub-demo

services:
  velocity:
    image: eclipse-temurin:21-jdk
    container_name: hub-demo-velocity
    working_dir: /app
    volumes:
      # Prebuilt binaries (provide from your build artifacts)
      - ./artifacts/velocity-proxy.jar:/app/velocity.jar:ro
      - ./artifacts/hub-velocity.jar:/app/plugins/hub.jar:ro
      # Configs
      - ./docker/velocity.docker.toml:/app/velocity.toml:ro
      - ./docker/velocity.forwarding.secret:/app/forwarding.secret:ro
      - ./docker/plugins.hub:/app/plugins/hub:ro
    command:
      - bash
      - -lc
      - |
        set -euo pipefail
        mkdir -p plugins
        java -Xms256m -Xmx512m \
          -jar /app/velocity.jar \
          -conf /app/velocity.toml \
          -forwarding-secret-file /app/forwarding.secret
    ports:
      - "25577:25577"
    networks:
      - hub

  lobby:
    image: eclipse-temurin:21-jdk
    container_name: hub-demo-lobby
    working_dir: /app
    volumes:
      - lobby-data:/app
      - ./artifacts/paper-server.jar:/app/paper.jar:ro
      - ./artifacts/hub-paper.jar:/app/plugins/HUB.jar:ro
      - ./docker/lobby.server.properties:/app/server.properties:ro
      - ./docker/plugins.hub/config.yml:/app/plugins/HUB/config.yml:ro
    command:
      - bash
      - -lc
      - |
        set -euo pipefail
        cd /app
        java -Xms512m -Xmx1G -jar /app/paper.jar --nogui
    networks:
      - hub

  ffa:
    image: eclipse-temurin:21-jdk
    container_name: hub-demo-ffa
    working_dir: /app
    environment:
      VELOCITY_SECRET: "secret"
    volumes:
      - ./artifacts/minestom-ffa-server.jar:/app/minestom-ffa.jar:ro
      - ./artifacts/hub-minestom-ffa.jar:/app/plugins/hub-ffa.jar:ro
      - ./docker/ffalobby.server.properties:/app/server.properties:ro
    command:
      - bash
      - -lc
      - |
        set -euo pipefail
        java -Xms256m -Xmx512m -jar /app/minestom-ffa.jar
    networks:
      - hub

networks:
  hub:
    driver: bridge

volumes:
  lobby-data:
