name: hub-dev

services:
  # Velocity proxy running your plugin via Gradle
  velocity:
    image: eclipse-temurin:21-jdk
    working_dir: /workspace
    volumes:
      - ./:/workspace
      # Use a Docker-specific Velocity config pointing to the limbo services
      - ./docker/velocity.docker.toml:/workspace/loader-velocity/run/velocity.toml
      - ./docker/velocity.forwarding.secret:/workspace/loader-velocity/run/forwarding.secret
      - ./docker/plugins.hub:/workspace/loader-velocity/run/plugins/hub
    environment:
      GRADLE_USER_HOME: /gradle-cache/velocity
      GRADLE_PROJECT_CACHE_DIR: /gradle-cache/velocity-project
      VELOCITY_VERSION: ${VELOCITY_VERSION:-latest}
      HUB_DEBUG: "true"
    command:
      - bash
      - -lc
      - |
        set -euo pipefail
        tmp=/workspace/gradlew-docker-$$$$
        trap 'rm -f "$$tmp"' EXIT
        tr -d '\r' < gradlew > "$$tmp"
        chmod +x "$$tmp"
        mkdir -p /gradle-cache/velocity
        # reset plugin configs to defaults each run
        rm -f /workspace/loader-velocity/run/plugins/hub/config.yml
        touch /workspace/loader-velocity/run/plugins/hub/data-dump.yml
        rm -rf /workspace/common/build /workspace/loader-velocity/build
        rm -rf /gradle-cache/velocity/caches/fabric-loom
        "$$tmp" --gradle-user-home /gradle-cache/velocity --project-cache-dir /gradle-cache/velocity-project :loader-velocity:runVelocity --no-daemon
    depends_on:
      - paper
      - minestom
      - ffa
    ports:
      - "25577:25577"
    networks:
      gateway:
        aliases:
          - hub-dev-velocity
      hub:

  # Paper server running via Gradle (run-paper plugin)
  paper:
    image: eclipse-temurin:21-jdk
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      GRADLE_USER_HOME: /gradle-cache/paper
      GRADLE_PROJECT_CACHE_DIR: /gradle-cache/paper-project
      PAPER_VERSION: ${PAPER_VERSION:-latest}
    command:
      - bash
      - -lc
      - |
        set -euo pipefail
        tmp=/workspace/gradlew-docker-$$$$
        trap 'rm -f "$$tmp"' EXIT
        tr -d '\r' < gradlew > "$$tmp"
        chmod +x "$$tmp"
        mkdir -p /gradle-cache/paper
        # reset plugin configs to defaults each run
        rm -f /workspace/loader-paper/run/plugins/HUB/config.yml
        rm -rf /workspace/common/build /workspace/loader-paper/build
        rm -rf /gradle-cache/paper/caches/fabric-loom
        "$$tmp" --gradle-user-home /gradle-cache/paper --project-cache-dir /gradle-cache/paper-project :loader-paper:runServer --no-daemon
    networks:
      - hub

  ffa:
    image: eclipse-temurin:25-jdk
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      GRADLE_USER_HOME: /gradle-cache/minestom-ffa
      GRADLE_PROJECT_CACHE_DIR: /gradle-cache/minestom-ffa-project
      VELOCITY_SECRET: "secret"
    command:
      - bash
      - -lc
      - |
        set -euo pipefail
        apt-get update -y >/dev/null && apt-get install -y --no-install-recommends openjdk-21-jdk-headless >/dev/null
        export JAVA_HOME_21=/usr/lib/jvm/java-21-openjdk-amd64
        export PATH="/usr/lib/jvm/java-21-openjdk-amd64/bin:$$PATH"
        tmp=/workspace/gradlew-docker-$$$$
        trap 'rm -f "$$tmp"' EXIT
        tr -d '\r' < gradlew > "$$tmp"
        chmod +x "$$tmp"
        rm -rf /gradle-cache/minestom-ffa
        mkdir -p /gradle-cache/minestom-ffa /gradle-cache/minestom-ffa-project
        "$$tmp" --gradle-user-home /gradle-cache/minestom-ffa --project-cache-dir /gradle-cache/minestom-ffa-project :loader-minestom-ffa:run --no-daemon
    networks:
      - hub

  fabric:
    image: eclipse-temurin:21-jdk
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      GRADLE_USER_HOME: /gradle-cache/fabric
      GRADLE_PROJECT_CACHE_DIR: /gradle-cache/fabric-project
      mcVersion: 1.21.11
      INCLUDE_FABRIC: "true"
    command:
      - bash
      - -lc
      - |
        set -euo pipefail
        tmp=/workspace/gradlew-docker-$$$$
        trap 'rm -f "$$tmp"' EXIT
        tr -d '\r' < gradlew > "$$tmp"
        chmod +x "$$tmp"
        mkdir -p /gradle-cache/fabric
        # reset plugin configs to defaults each run
        rm -f /workspace/loader-fabric/run/config/hub.yaml
        rm -rf /workspace/common/build /workspace/loader-fabric/build
        rm -rf /gradle-cache/fabric/caches/fabric-loom
        "$$tmp" --gradle-user-home /gradle-cache/fabric --project-cache-dir /gradle-cache/fabric-project :loader-fabric:runServer --no-daemon
    networks:
      - hub

  neoforge:
    image: eclipse-temurin:21-jdk
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      GRADLE_USER_HOME: /gradle-cache/neoforge
      GRADLE_PROJECT_CACHE_DIR: /gradle-cache/neoforge-project
      mcVersion: 1.21.10
      INCLUDE_NEOFORGE: "true"
    command:
      - bash
      - -lc
      - |
        set -euo pipefail
        tmp=/workspace/gradlew-docker-$$$$
        trap 'rm -f "$$tmp"' EXIT
        tr -d '\r' < gradlew > "$$tmp"
        chmod +x "$$tmp"
        rm -rf /gradle-cache/neoforge
        mkdir -p /gradle-cache/neoforge
        # reset plugin configs to defaults each run
        rm -f /workspace/loader-neoforge/run/config/hub.yaml
        rm -rf /workspace/common/build /workspace/loader-neoforge/build /workspace/loader-neoforge/run/mods
        rm -rf /gradle-cache/neoforge/caches/fabric-loom
        rm -rf /gradle-cache/neoforge/caches/neoformruntime
        "$$tmp" --gradle-user-home /gradle-cache/neoforge --project-cache-dir /gradle-cache/neoforge-project :loader-neoforge:runServer --no-daemon
    networks:
      - hub

  minestom:
    image: eclipse-temurin:25-jdk
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      GRADLE_USER_HOME: /gradle-cache/minestom
      GRADLE_PROJECT_CACHE_DIR: /gradle-cache/minestom-project
      VELOCITY_SECRET: "secret"
    command:
      - bash
      - -lc
      - |
        set -euo pipefail
        apt-get update -y >/dev/null && apt-get install -y --no-install-recommends openjdk-21-jdk-headless >/dev/null
        export JAVA_HOME_21=/usr/lib/jvm/java-21-openjdk-amd64
        export PATH="/usr/lib/jvm/java-21-openjdk-amd64/bin:$$PATH"
        tmp=/workspace/gradlew-docker-$$$$
        trap 'rm -f "$$tmp"' EXIT
        tr -d '\r' < gradlew > "$$tmp"
        chmod +x "$$tmp"
        rm -rf /gradle-cache/minestom
        mkdir -p /gradle-cache/minestom
        # reset plugin configs to defaults each run
        rm -f /workspace/loader-minestom/run/config/hub.yaml
        rm -rf /workspace/common/build /workspace/loader-minestom/build /workspace/loader-minestom/run
        "$$tmp" --gradle-user-home /gradle-cache/minestom --project-cache-dir /gradle-cache/minestom-project :loader-minestom:run --no-daemon
    networks:
      - hub

networks:
  hub:
    driver: bridge
  gateway:
    external: true
